module.exports = [
    [0, 0], // Nop
    [0, 0], // Undef
    [0, 0], // SourceContinued
    [1, 0], // Source
    [0, 0], // SourceExtension
    [0, 0], // Name
    [0, 0], // MemberName
    [0, 0], // String
    [1, 0], // Line
    [0, 0], // #9
    [0, 0], // Extension
    [0, 0], // ExtInstImport
    [1, 0], // ExtInst
    [1, 2], // VectorShuffleCompact - new in SMOLV
    [1, 0], // MemoryModel
    [1, 0], // EntryPoint
    [1, 0], // ExecutionMode
    [1, 0], // Capability
    [0, 0], // #18
    [1, 0], // TypeVoid
    [1, 0], // TypeBool
    [1, 0], // TypeInt
    [1, 0], // TypeFloat
    [1, 0], // TypeVector
    [1, 0], // TypeMatrix
    [1, 0], // TypeImage
    [1, 0], // TypeSampler
    [1, 0], // TypeSampledImage
    [1, 0], // TypeArray
    [1, 0], // TypeRuntimeArray
    [1, 0], // TypeStruct
    [1, 0], // TypeOpaque
    [1, 0], // TypePointer
    [1, 0], // TypeFunction
    [1, 0], // TypeEvent
    [1, 0], // TypeDeviceEvent
    [1, 0], // TypeReserveId
    [1, 0], // TypeQueue
    [1, 0], // TypePipe
    [1, 0], // TypeForwardPointer
    [0, 0], // #40
    [0, 0], // ConstantTrue
    [0, 0], // ConstantFalse
    [0, 0], // Constant
    [0, 9], // ConstantComposite
    [1, 0], // ConstantSampler
    [0, 0], // ConstantNull
    [0, 0], // #47
    [0, 0], // SpecConstantTrue
    [0, 0], // SpecConstantFalse
    [0, 0], // SpecConstant
    [0, 9], // SpecConstantComposite
    [0, 0], // SpecConstantOp
    [0, 0], // #53
    [1, 0], // Function
    [0, 0], // FunctionParameter
    [0, 0], // FunctionEnd
    [0, 9], // FunctionCall
    [0, 0], // #58
    [1, 0], // Variable
    [0, 0], // ImageTexelPointer
    [1, 1], // Load
    [1, 2], // Store
    [0, 0], // CopyMemory
    [0, 0], // CopyMemorySized
    [1, 0], // AccessChain
    [0, 0], // InBoundsAccessChain
    [0, 0], // PtrAccessChain
    [0, 0], // ArrayLength
    [0, 0], // GenericPtrMemSemantics
    [0, 0], // InBoundsPtrAccessChain
    [1, 0], // Decorate
    [1, 0], // MemberDecorate
    [0, 0], // DecorationGroup
    [0, 0], // GroupDecorate
    [0, 0], // GroupMemberDecorate
    [0, 0], // #76
    [1, 1], // VectorExtractDynamic
    [1, 2], // VectorInsertDynamic
    [1, 2], // VectorShuffle
    [0, 9], // CompositeConstruct
    [1, 1], // CompositeExtract
    [1, 2], // CompositeInsert
    [0, 1], // CopyObject
    [0, 0], // Transpose
    [0, 0], // #85
    [0, 0], // SampledImage
    [1, 2], // ImageSampleImplicitLod
    [1, 2], // ImageSampleExplicitLod
    [1, 3], // ImageSampleDrefImplicitLod
    [1, 3], // ImageSampleDrefExplicitLod
    [1, 2], // ImageSampleProjImplicitLod
    [1, 2], // ImageSampleProjExplicitLod
    [1, 3], // ImageSampleProjDrefImplicitLod
    [1, 3], // ImageSampleProjDrefExplicitLod
    [1, 2], // ImageFetch
    [1, 3], // ImageGather
    [1, 3], // ImageDrefGather
    [1, 2], // ImageRead
    [1, 3], // ImageWrite
    [0, 1], // Image
    [0, 1], // ImageQueryFormat
    [0, 1], // ImageQueryOrder
    [0, 2], // ImageQuerySizeLod
    [0, 1], // ImageQuerySize
    [0, 2], // ImageQueryLod
    [0, 1], // ImageQueryLevels
    [0, 1], // ImageQuerySamples
    [0, 0], // #108
    [0, 1], // ConvertFToU
    [0, 1], // ConvertFToS
    [0, 1], // ConvertSToF
    [0, 1], // ConvertUToF
    [0, 1], // UConvert
    [0, 1], // SConvert
    [0, 1], // FConvert
    [0, 1], // QuantizeToF16
    [0, 1], // ConvertPtrToU
    [0, 1], // SatConvertSToU
    [0, 1], // SatConvertUToS
    [0, 1], // ConvertUToPtr
    [0, 1], // PtrCastToGeneric
    [0, 1], // GenericCastToPtr
    [1, 1], // GenericCastToPtrExplicit
    [0, 1], // Bitcast
    [0, 0], // #125
    [0, 1], // SNegate
    [0, 1], // FNegate
    [0, 2], // IAdd
    [0, 2], // FAdd
    [0, 2], // ISub
    [0, 2], // FSub
    [0, 2], // IMul
    [0, 2], // FMul
    [0, 2], // UDiv
    [0, 2], // SDiv
    [0, 2], // FDiv
    [0, 2], // UMod
    [0, 2], // SRem
    [0, 2], // SMod
    [0, 2], // FRem
    [0, 2], // FMod
    [0, 2], // VectorTimesScalar
    [0, 2], // MatrixTimesScalar
    [0, 2], // VectorTimesMatrix
    [0, 2], // MatrixTimesVector
    [0, 2], // MatrixTimesMatrix
    [0, 2], // OuterProduct
    [0, 2], // Dot
    [0, 2], // IAddCarry
    [0, 2], // ISubBorrow
    [0, 2], // UMulExtended
    [0, 2], // SMulExtended
    [0, 0], // #153
    [0, 1], // Any
    [0, 1], // All
    [0, 1], // IsNan
    [0, 1], // IsInf
    [0, 1], // IsFinite
    [0, 1], // IsNormal
    [0, 1], // SignBitSet
    [0, 2], // LessOrGreater
    [0, 2], // Ordered
    [0, 2], // Unordered
    [0, 2], // LogicalEqual
    [0, 2], // LogicalNotEqual
    [0, 2], // LogicalOr
    [0, 2], // LogicalAnd
    [0, 1], // LogicalNot
    [0, 3], // Select
    [0, 2], // IEqual
    [0, 2], // INotEqual
    [0, 2], // UGreaterThan
    [0, 2], // SGreaterThan
    [0, 2], // UGreaterThanEqual
    [0, 2], // SGreaterThanEqual
    [0, 2], // ULessThan
    [0, 2], // SLessThan
    [0, 2], // ULessThanEqual
    [0, 2], // SLessThanEqual
    [0, 2], // FOrdEqual
    [0, 2], // FUnordEqual
    [0, 2], // FOrdNotEqual
    [0, 2], // FUnordNotEqual
    [0, 2], // FOrdLessThan
    [0, 2], // FUnordLessThan
    [0, 2], // FOrdGreaterThan
    [0, 2], // FUnordGreaterThan
    [0, 2], // FOrdLessThanEqual
    [0, 2], // FUnordLessThanEqual
    [0, 2], // FOrdGreaterThanEqual
    [0, 2], // FUnordGreaterThanEqual
    [0, 0], // #192
    [0, 0], // #193
    [0, 2], // ShiftRightLogical
    [0, 2], // ShiftRightArithmetic
    [0, 2], // ShiftLeftLogical
    [0, 2], // BitwiseOr
    [0, 2], // BitwiseXor
    [0, 2], // BitwiseAnd
    [0, 1], // Not
    [0, 4], // BitFieldInsert
    [0, 3], // BitFieldSExtract
    [0, 3], // BitFieldUExtract
    [0, 1], // BitReverse
    [0, 1], // BitCount
    [0, 0], // #206
    [0, 0], // DPdx
    [0, 0], // DPdy
    [0, 0], // Fwidth
    [0, 0], // DPdxFine
    [0, 0], // DPdyFine
    [0, 0], // FwidthFine
    [0, 0], // DPdxCoarse
    [0, 0], // DPdyCoarse
    [0, 0], // FwidthCoarse
    [0, 0], // #216
    [0, 0], // #217
    [0, 0], // EmitVertex
    [0, 0], // EndPrimitive
    [0, 0], // EmitStreamVertex
    [0, 0], // EndStreamPrimitive
    [0, 0], // #222
    [0, 0], // #223
    [0, 3], // ControlBarrier
    [0, 2], // MemoryBarrier
    [0, 0], // #226
    [0, 0], // AtomicLoad
    [0, 0], // AtomicStore
    [0, 0], // AtomicExchange
    [0, 0], // AtomicCompareExchange
    [0, 0], // AtomicCompareExchangeWeak
    [0, 0], // AtomicIIncrement
    [0, 0], // AtomicIDecrement
    [0, 0], // AtomicIAdd
    [0, 0], // AtomicISub
    [0, 0], // AtomicSMin
    [0, 0], // AtomicUMin
    [0, 0], // AtomicSMax
    [0, 0], // AtomicUMax
    [0, 0], // AtomicAnd
    [0, 0], // AtomicOr
    [0, 0], // AtomicXor
    [0, 0], // #243
    [0, 0], // #244
    [0, 0], // Phi
    [1, 2], // LoopMerge
    [1, 1], // SelectionMerge
    [0, 0], // Label
    [0, 1], // Branch
    [1, 3], // BranchConditional
    [0, 0], // Switch
    [0, 0], // Kill
    [0, 0], // Return
    [0, 0], // ReturnValue
    [0, 0], // Unreachable
    [0, 0], // LifetimeStart
    [0, 0], // LifetimeStop
    [0, 0], // #258
    [0, 0], // GroupAsyncCopy
    [0, 0], // GroupWaitEvents
    [0, 0], // GroupAll
    [0, 0], // GroupAny
    [0, 0], // GroupBroadcast
    [0, 0], // GroupIAdd
    [0, 0], // GroupFAdd
    [0, 0], // GroupFMin
    [0, 0], // GroupUMin
    [0, 0], // GroupSMin
    [0, 0], // GroupFMax
    [0, 0], // GroupUMax
    [0, 0], // GroupSMax
    [0, 0], // #272
    [0, 0], // #273
    [0, 0], // ReadPipe
    [0, 0], // WritePipe
    [0, 0], // ReservedReadPipe
    [0, 0], // ReservedWritePipe
    [0, 0], // ReserveReadPipePackets
    [0, 0], // ReserveWritePipePackets
    [0, 0], // CommitReadPipe
    [0, 0], // CommitWritePipe
    [0, 0], // IsValidReserveId
    [0, 0], // GetNumPipePackets
    [0, 0], // GetMaxPipePackets
    [0, 0], // GroupReserveReadPipePackets
    [0, 0], // GroupReserveWritePipePackets
    [0, 0], // GroupCommitReadPipe
    [0, 0], // GroupCommitWritePipe
    [0, 0], // #289
    [0, 0], // #290
    [0, 0], // EnqueueMarker
    [0, 0], // EnqueueKernel
    [0, 0], // GetKernelNDrangeSubGroupCount
    [0, 0], // GetKernelNDrangeMaxSubGroupSize
    [0, 0], // GetKernelWorkGroupSize
    [0, 0], // GetKernelPreferredWorkGroupSizeMultipl
    [0, 0], // RetainEvent
    [0, 0], // ReleaseEvent
    [0, 0], // CreateUserEvent
    [0, 0], // IsValidEvent
    [0, 0], // SetUserEventStatus
    [0, 0], // CaptureEventProfilingInfo
    [0, 0], // GetDefaultQueue
    [0, 0], // BuildNDRange
    [1, 2], // ImageSparseSampleImplicitLod
    [1, 2], // ImageSparseSampleExplicitLod
    [1, 3], // ImageSparseSampleDrefImplicitLod
    [1, 3], // ImageSparseSampleDrefExplicitLod
    [1, 2], // ImageSparseSampleProjImplicitLod
    [1, 2], // ImageSparseSampleProjExplicitLod
    [1, 3], // ImageSparseSampleProjDrefImplicitLod
    [1, 3], // ImageSparseSampleProjDrefExplicitLod
    [1, 2], // ImageSparseFetch
    [1, 3], // ImageSparseGather
    [1, 3], // ImageSparseDrefGather
    [0, 1], // ImageSparseTexelsResident
    [0, 0], // NoLine
    [0, 0], // AtomicFlagTestAndSet
    [0, 0], // AtomicFlagClear
    [0, 0], // ImageSparseRead
    [0, 0], // SizeOf
    [0, 0], // TypePipeStorage
    [0, 0], // ConstantPipeStorage
    [0, 0], // CreatePipeFromPipeStorage
    [0, 0], // GetKernelLocalSizeForSubgroupCount
    [0, 0], // GetKernelMaxNumSubgroups
    [0, 0], // TypeNamedBarrier
    [1, 0], // NamedBarrierInitialize
    [1, 2], // MemoryNamedBarrier
    [0, 0], // ModuleProcessed
];
