module.exports = [
    [0, 0], // Nop
    [0, 0], // Undef
    [0, 0], // SourceContinued
    [0, 1], // Source
    [0, 0], // SourceExtension
    [0, 0], // Name
    [0, 0], // MemberName
    [0, 0], // String
    [0, 1], // Line
    [0, 0], // #9
    [0, 0], // Extension
    [0, 0], // ExtInstImport
    [0, 1], // ExtInst
    [2, 1], // VectorShuffleCompact - new in SMOLV
    [0, 1], // MemoryModel
    [0, 1], // EntryPoint
    [0, 1], // ExecutionMode
    [0, 1], // Capability
    [0, 0], // #18
    [0, 1], // TypeVoid
    [0, 1], // TypeBool
    [0, 1], // TypeInt
    [0, 1], // TypeFloat
    [0, 1], // TypeVector
    [0, 1], // TypeMatrix
    [0, 1], // TypeImage
    [0, 1], // TypeSampler
    [0, 1], // TypeSampledImage
    [0, 1], // TypeArray
    [0, 1], // TypeRuntimeArray
    [0, 1], // TypeStruct
    [0, 1], // TypeOpaque
    [0, 1], // TypePointer
    [0, 1], // TypeFunction
    [0, 1], // TypeEvent
    [0, 1], // TypeDeviceEvent
    [0, 1], // TypeReserveId
    [0, 1], // TypeQueue
    [0, 1], // TypePipe
    [0, 1], // TypeForwardPointer
    [0, 0], // #40
    [0, 0], // ConstantTrue
    [0, 0], // ConstantFalse
    [0, 0], // Constant
    [9, 0], // ConstantComposite
    [0, 1], // ConstantSampler
    [0, 0], // ConstantNull
    [0, 0], // #47
    [0, 0], // SpecConstantTrue
    [0, 0], // SpecConstantFalse
    [0, 0], // SpecConstant
    [9, 0], // SpecConstantComposite
    [0, 0], // SpecConstantOp
    [0, 0], // #53
    [0, 1], // Function
    [0, 0], // FunctionParameter
    [0, 0], // FunctionEnd
    [9, 0], // FunctionCall
    [0, 0], // #58
    [0, 1], // Variable
    [0, 0], // ImageTexelPointer
    [1, 1], // Load
    [2, 1], // Store
    [0, 0], // CopyMemory
    [0, 0], // CopyMemorySized
    [0, 1], // AccessChain
    [0, 0], // InBoundsAccessChain
    [0, 0], // PtrAccessChain
    [0, 0], // ArrayLength
    [0, 0], // GenericPtrMemSemantics
    [0, 0], // InBoundsPtrAccessChain
    [0, 1], // Decorate
    [0, 1], // MemberDecorate
    [0, 0], // DecorationGroup
    [0, 0], // GroupDecorate
    [0, 0], // GroupMemberDecorate
    [0, 0], // #76
    [1, 1], // VectorExtractDynamic
    [2, 1], // VectorInsertDynamic
    [2, 1], // VectorShuffle
    [9, 0], // CompositeConstruct
    [1, 1], // CompositeExtract
    [2, 1], // CompositeInsert
    [1, 0], // CopyObject
    [0, 0], // Transpose
    [0, 0], // #85
    [0, 0], // SampledImage
    [2, 1], // ImageSampleImplicitLod
    [2, 1], // ImageSampleExplicitLod
    [3, 1], // ImageSampleDrefImplicitLod
    [3, 1], // ImageSampleDrefExplicitLod
    [2, 1], // ImageSampleProjImplicitLod
    [2, 1], // ImageSampleProjExplicitLod
    [3, 1], // ImageSampleProjDrefImplicitLod
    [3, 1], // ImageSampleProjDrefExplicitLod
    [2, 1], // ImageFetch
    [3, 1], // ImageGather
    [3, 1], // ImageDrefGather
    [2, 1], // ImageRead
    [3, 1], // ImageWrite
    [1, 0], // Image
    [1, 0], // ImageQueryFormat
    [1, 0], // ImageQueryOrder
    [2, 0], // ImageQuerySizeLod
    [1, 0], // ImageQuerySize
    [2, 0], // ImageQueryLod
    [1, 0], // ImageQueryLevels
    [1, 0], // ImageQuerySamples
    [0, 0], // #108
    [1, 0], // ConvertFToU
    [1, 0], // ConvertFToS
    [1, 0], // ConvertSToF
    [1, 0], // ConvertUToF
    [1, 0], // UConvert
    [1, 0], // SConvert
    [1, 0], // FConvert
    [1, 0], // QuantizeToF16
    [1, 0], // ConvertPtrToU
    [1, 0], // SatConvertSToU
    [1, 0], // SatConvertUToS
    [1, 0], // ConvertUToPtr
    [1, 0], // PtrCastToGeneric
    [1, 0], // GenericCastToPtr
    [1, 1], // GenericCastToPtrExplicit
    [1, 0], // Bitcast
    [0, 0], // #125
    [1, 0], // SNegate
    [1, 0], // FNegate
    [2, 0], // IAdd
    [2, 0], // FAdd
    [2, 0], // ISub
    [2, 0], // FSub
    [2, 0], // IMul
    [2, 0], // FMul
    [2, 0], // UDiv
    [2, 0], // SDiv
    [2, 0], // FDiv
    [2, 0], // UMod
    [2, 0], // SRem
    [2, 0], // SMod
    [2, 0], // FRem
    [2, 0], // FMod
    [2, 0], // VectorTimesScalar
    [2, 0], // MatrixTimesScalar
    [2, 0], // VectorTimesMatrix
    [2, 0], // MatrixTimesVector
    [2, 0], // MatrixTimesMatrix
    [2, 0], // OuterProduct
    [2, 0], // Dot
    [2, 0], // IAddCarry
    [2, 0], // ISubBorrow
    [2, 0], // UMulExtended
    [2, 0], // SMulExtended
    [0, 0], // #153
    [1, 0], // Any
    [1, 0], // All
    [1, 0], // IsNan
    [1, 0], // IsInf
    [1, 0], // IsFinite
    [1, 0], // IsNormal
    [1, 0], // SignBitSet
    [2, 0], // LessOrGreater
    [2, 0], // Ordered
    [2, 0], // Unordered
    [2, 0], // LogicalEqual
    [2, 0], // LogicalNotEqual
    [2, 0], // LogicalOr
    [2, 0], // LogicalAnd
    [1, 0], // LogicalNot
    [3, 0], // Select
    [2, 0], // IEqual
    [2, 0], // INotEqual
    [2, 0], // UGreaterThan
    [2, 0], // SGreaterThan
    [2, 0], // UGreaterThanEqual
    [2, 0], // SGreaterThanEqual
    [2, 0], // ULessThan
    [2, 0], // SLessThan
    [2, 0], // ULessThanEqual
    [2, 0], // SLessThanEqual
    [2, 0], // FOrdEqual
    [2, 0], // FUnordEqual
    [2, 0], // FOrdNotEqual
    [2, 0], // FUnordNotEqual
    [2, 0], // FOrdLessThan
    [2, 0], // FUnordLessThan
    [2, 0], // FOrdGreaterThan
    [2, 0], // FUnordGreaterThan
    [2, 0], // FOrdLessThanEqual
    [2, 0], // FUnordLessThanEqual
    [2, 0], // FOrdGreaterThanEqual
    [2, 0], // FUnordGreaterThanEqual
    [0, 0], // #192
    [0, 0], // #193
    [2, 0], // ShiftRightLogical
    [2, 0], // ShiftRightArithmetic
    [2, 0], // ShiftLeftLogical
    [2, 0], // BitwiseOr
    [2, 0], // BitwiseXor
    [2, 0], // BitwiseAnd
    [1, 0], // Not
    [4, 0], // BitFieldInsert
    [3, 0], // BitFieldSExtract
    [3, 0], // BitFieldUExtract
    [1, 0], // BitReverse
    [1, 0], // BitCount
    [0, 0], // #206
    [0, 0], // DPdx
    [0, 0], // DPdy
    [0, 0], // Fwidth
    [0, 0], // DPdxFine
    [0, 0], // DPdyFine
    [0, 0], // FwidthFine
    [0, 0], // DPdxCoarse
    [0, 0], // DPdyCoarse
    [0, 0], // FwidthCoarse
    [0, 0], // #216
    [0, 0], // #217
    [0, 0], // EmitVertex
    [0, 0], // EndPrimitive
    [0, 0], // EmitStreamVertex
    [0, 0], // EndStreamPrimitive
    [0, 0], // #222
    [0, 0], // #223
    [3, 0], // ControlBarrier
    [2, 0], // MemoryBarrier
    [0, 0], // #226
    [0, 0], // AtomicLoad
    [0, 0], // AtomicStore
    [0, 0], // AtomicExchange
    [0, 0], // AtomicCompareExchange
    [0, 0], // AtomicCompareExchangeWeak
    [0, 0], // AtomicIIncrement
    [0, 0], // AtomicIDecrement
    [0, 0], // AtomicIAdd
    [0, 0], // AtomicISub
    [0, 0], // AtomicSMin
    [0, 0], // AtomicUMin
    [0, 0], // AtomicSMax
    [0, 0], // AtomicUMax
    [0, 0], // AtomicAnd
    [0, 0], // AtomicOr
    [0, 0], // AtomicXor
    [0, 0], // #243
    [0, 0], // #244
    [0, 0], // Phi
    [2, 1], // LoopMerge
    [1, 1], // SelectionMerge
    [0, 0], // Label
    [1, 0], // Branch
    [3, 1], // BranchConditional
    [0, 0], // Switch
    [0, 0], // Kill
    [0, 0], // Return
    [0, 0], // ReturnValue
    [0, 0], // Unreachable
    [0, 0], // LifetimeStart
    [0, 0], // LifetimeStop
    [0, 0], // #258
    [0, 0], // GroupAsyncCopy
    [0, 0], // GroupWaitEvents
    [0, 0], // GroupAll
    [0, 0], // GroupAny
    [0, 0], // GroupBroadcast
    [0, 0], // GroupIAdd
    [0, 0], // GroupFAdd
    [0, 0], // GroupFMin
    [0, 0], // GroupUMin
    [0, 0], // GroupSMin
    [0, 0], // GroupFMax
    [0, 0], // GroupUMax
    [0, 0], // GroupSMax
    [0, 0], // #272
    [0, 0], // #273
    [0, 0], // ReadPipe
    [0, 0], // WritePipe
    [0, 0], // ReservedReadPipe
    [0, 0], // ReservedWritePipe
    [0, 0], // ReserveReadPipePackets
    [0, 0], // ReserveWritePipePackets
    [0, 0], // CommitReadPipe
    [0, 0], // CommitWritePipe
    [0, 0], // IsValidReserveId
    [0, 0], // GetNumPipePackets
    [0, 0], // GetMaxPipePackets
    [0, 0], // GroupReserveReadPipePackets
    [0, 0], // GroupReserveWritePipePackets
    [0, 0], // GroupCommitReadPipe
    [0, 0], // GroupCommitWritePipe
    [0, 0], // #289
    [0, 0], // #290
    [0, 0], // EnqueueMarker
    [0, 0], // EnqueueKernel
    [0, 0], // GetKernelNDrangeSubGroupCount
    [0, 0], // GetKernelNDrangeMaxSubGroupSize
    [0, 0], // GetKernelWorkGroupSize
    [0, 0], // GetKernelPreferredWorkGroupSizeMultipl
    [0, 0], // RetainEvent
    [0, 0], // ReleaseEvent
    [0, 0], // CreateUserEvent
    [0, 0], // IsValidEvent
    [0, 0], // SetUserEventStatus
    [0, 0], // CaptureEventProfilingInfo
    [0, 0], // GetDefaultQueue
    [0, 0], // BuildNDRange
    [2, 1], // ImageSparseSampleImplicitLod
    [2, 1], // ImageSparseSampleExplicitLod
    [3, 1], // ImageSparseSampleDrefImplicitLod
    [3, 1], // ImageSparseSampleDrefExplicitLod
    [2, 1], // ImageSparseSampleProjImplicitLod
    [2, 1], // ImageSparseSampleProjExplicitLod
    [3, 1], // ImageSparseSampleProjDrefImplicitLod
    [3, 1], // ImageSparseSampleProjDrefExplicitLod
    [2, 1], // ImageSparseFetch
    [3, 1], // ImageSparseGather
    [3, 1], // ImageSparseDrefGather
    [1, 0], // ImageSparseTexelsResident
    [0, 0], // NoLine
    [0, 0], // AtomicFlagTestAndSet
    [0, 0], // AtomicFlagClear
    [0, 0], // ImageSparseRead
    [0, 0], // SizeOf
    [0, 0], // TypePipeStorage
    [0, 0], // ConstantPipeStorage
    [0, 0], // CreatePipeFromPipeStorage
    [0, 0], // GetKernelLocalSizeForSubgroupCount
    [0, 0], // GetKernelMaxNumSubgroups
    [0, 0], // TypeNamedBarrier
    [0, 1], // NamedBarrierInitialize
    [2, 1], // MemoryNamedBarrier
    [0, 0], // ModuleProcessed
];
